export const DEFAULT_CHECKLIST_ITEMS: { categorie: string; libelle: string }[] = [
  { categorie: "Entrée & clés", libelle: "Jeu de clés / badges remis" },
  { categorie: "Entrée & clés", libelle: "Boîte à clés / digicode fonctionnel" },
  { categorie: "Entrée & clés", libelle: "Wifi (accès et débit)" },
  { categorie: "Cuisine", libelle: "Réfrigérateur / congélateur" },
  { categorie: "Cuisine", libelle: "Four / plaques de cuisson" },
  { categorie: "Cuisine", libelle: "Micro-ondes" },
  { categorie: "Cuisine", libelle: "Vaisselle et ustensiles complets" },
  { categorie: "Cuisine", libelle: "Lave-vaisselle" },
  { categorie: "Salon", libelle: "Télévision / box TV" },
  { categorie: "Salon", libelle: "Climatisation / ventilateurs" },
  { categorie: "Salon", libelle: "Mobilier (canapé, table, chaises)" },
  { categorie: "Salon", libelle: "Volets roulants automatiques" },
  { categorie: "Chambre 1", libelle: "Literie complète et propre" },
  { categorie: "Chambre 1", libelle: "Armoires / rangements" },
  { categorie: "Chambre 1", libelle: "Volets roulants automatiques" },
  { categorie: "Chambre 2", libelle: "Literie complète et propre" },
  { categorie: "Chambre 2", libelle: "Armoires / rangements" },
  { categorie: "Chambre 2", libelle: "Volets roulants automatiques" },
  { categorie: "Chambre 3", libelle: "Literie complète et propre" },
  { categorie: "Chambre 3", libelle: "Armoires / rangements" },
  { categorie: "Chambre 3", libelle: "Volets roulants automatiques" },
  { categorie: "Chambre 4", libelle: "Literie complète et propre" },
  { categorie: "Chambre 4", libelle: "Armoires / rangements" },
  { categorie: "Chambre 4", libelle: "Volets roulants automatiques" },
  { categorie: "Salle de bain", libelle: "Robinetterie / eau chaude" },
  { categorie: "Salle de bain", libelle: "Sèche-cheveux" },
  { categorie: "Salle de bain", libelle: "Serviettes fournies" },
  { categorie: "Piscine", libelle: "Fonctionnement (pompe, filtration)" },
  { categorie: "Piscine", libelle: "Propreté de l'eau" },
  { categorie: "Piscine", libelle: "Sécurité (barrière / alarme)" },
  { categorie: "Extérieur", libelle: "Mobilier de jardin / terrasse" },
  { categorie: "Extérieur", libelle: "Portail / accès véhicule" },
  { categorie: "Extérieur", libelle: "Jardin & arrosage automatique" },
  { categorie: "Bien-être", libelle: "Hammam / spa" },
  { categorie: "Équipements techniques", libelle: "Climatisation (chaque pièce)" },
  { categorie: "Équipements techniques", libelle: "Chauffage / chauffe-eau" },
  { categorie: "Équipements techniques", libelle: "Groupe électrogène de secours" },
  { categorie: "Sécurité", libelle: "Détecteur de fumée fonctionnel" },
  { categorie: "Sécurité", libelle: "Extincteur présent et valide" },
  { categorie: "Général", libelle: "État de propreté général" },
  { categorie: "Général", libelle: "Dommages visibles (murs, sols, vitres)" },
];
