export const DEFAULT_CHECKLIST_ITEMS: { categorie: string; libelle: string }[] = [
  { categorie: "Entrée & clés", libelle: "Jeu de clés / badges remis" },
  { categorie: "Entrée & clés", libelle: "Boîte à clés / digicode fonctionnel" },
  { categorie: "Entrée & clés", libelle: "Wifi (accès et débit)" },
  { categorie: "Cuisine", libelle: "Réfrigérateur / congélateur" },
  { categorie: "Cuisine", libelle: "Four / plaques de cuisson" },
  { categorie: "Cuisine", libelle: "Micro-ondes" },
  { categorie: "Cuisine", libelle: "Vaisselle et ustensiles complets" },
  { categorie: "Cuisine", libelle: "Lave-vaisselle" },
  { categorie: "Salon", libelle: "Télévision / box TV" },
  { categorie: "Salon", libelle: "Climatisation / ventilateurs" },
  { categorie: "Salon", libelle: "Mobilier (canapé, table, chaises)" },
  { categorie: "Chambres", libelle: "Literie complète et propre" },
  { categorie: "Chambres", libelle: "Armoires / rangements" },
  { categorie: "Salle de bain", libelle: "Robinetterie / eau chaude" },
  { categorie: "Salle de bain", libelle: "Sèche-cheveux" },
  { categorie: "Salle de bain", libelle: "Serviettes fournies" },
  { categorie: "Extérieur", libelle: "Piscine (eau, filtration, sécurité)" },
  { categorie: "Extérieur", libelle: "Mobilier de jardin / terrasse" },
  { categorie: "Extérieur", libelle: "Portail / accès véhicule" },
  { categorie: "Sécurité", libelle: "Détecteur de fumée fonctionnel" },
  { categorie: "Sécurité", libelle: "Extincteur présent et valide" },
  { categorie: "Général", libelle: "État de propreté général" },
  { categorie: "Général", libelle: "Dommages visibles (murs, sols, vitres)" },
];
